#%RAML 0.8
---
title: Beer API
version: v1
/beer/styles:
  get:
    description: 'return a list of beer styles'
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/styles.schema
            example: |
              {
                "beer" : [
                  "Beligian",
                  "Lager",
                  "Wiess"
                ]
              }
